Add validation functions
emanguy/amp-hex-translator pull request #39
Opened 2016-11-29 21:41 UTC by emanguy

* Add "0x on the front" validation
 * Add "has only hex characters" validation

2016-11-29 22:13 UTC, gti28 requested changes

2016-11-29 22:13 UTC, gti28 commented on src/js/validation/has0x/validateHas0x.js
> +}
I think in the requirements we said the prefix is optional

2016-11-29 22:37 UTC, emanguy commented on src/js/validation/has0x/validateHas0x.js
> +}
If that's the case I can change it

2016-11-29 22:46 UTC, gti28 commented on src/js/validation/has0x/validateHas0x.js
> +}
looks like it was in the design, not the requirements, so I'm fine with making 0x required, we can update the design to match

2016-11-29 22:46 UTC, gti28 approved these changes

2016-11-30 02:00 UTC, emanguy commented on src/js/validation/has0x/validateHas0x.js
> +}
I'll just remove the 0x validation

2016-12-04 17:01 UTC, merged